teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.8
        offset: 0
      -
        axis: 0
        target: angular.z
        scale: 0.5

  stop:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [5]
    message_value:
      -
        target: linear.x
        value: 0.0
      -
        target: angular.z
        value: 0.0
      -
        target: linear.y
        value: 0.0
  activation:
      type: topic
      message_type: std_msgs/Bool 
      topic_name: /activation
      deadman_buttons: [6]
      message_value:
        -
          target: data
          value: True
